### ISSUE TITLE
How to get this to work?

### ISSUE THREAD

**Issue by vistalba** [KoKia13/HomeAssistant-Landroid#1]
Hi

I used the Landroid Bridge until now. But this is really overkill for me. I just want to get the stauts. May later "start" / "home" function. 

So I tried to use your REST integration but without luck.

May you can explain how to get this work? What steps do I've to do?

Thanks

**Comment by KoKia13** [comment]
Hi,

it was just to share the code to some guys at the beginning,
Same for the bridge is overkill, and I was banned regularly.
Too complex for the simple things I need.

Voilà: https://github.com/KoKia13/HomeAssistant-Landroid/blob/master/README.md

;)
